name: Generated APK - SportApp

env:
  main_project_module: app
  playstore_name: SportApp
  PROJECT_ID: sportapp-grupo2

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Construir el proyecto
        run: ./gradlew build
      - name: Construir el APK Debug
        run: ./gradlew assembleDebug
