---
name: Validar pruebas unitarias
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - synchronize
      - opened
      - edited
jobs:
  correr-pruebas-unitarias-mobile:
    name: correr-pruebas-unitarias-mobile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11.0.15
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.15

        # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

